class WsEventType:
    MESSAGE_CREATED = "message.created"
    MESSAGE_ACCEPTED = "message.accepted"
    REPLY_FAILED = "reply.failed"


class GroupTaskEventType:
    RUN_CREATED = "run.created"
    RUN_FINALIZED = "run.finalized"
    RUN_REPLAN_STARTED = "run.replan.started"
    RUN_REPLAN_APPLIED = "run.replan.applied"
    DAG_UPDATED = "dag.updated"
    ORCHESTRATOR_PLAN_APPLIED = "orchestrator.plan_applied"
    MANAGER_PLANNING_LLM_STARTED = "manager.planning.llm.started"
    NODE_CLAIMED = "node.claimed"
    NODE_AUTO_ASSIGNED = "node.auto_assigned"
    NODE_SMART_AUTO_ASSIGNED = "node.smart_auto_assigned"
    NODE_COMPLETED = "node.completed"
    NODE_REVIEWED = "node.reviewed"
    NODE_AUTO_REVIEWED = "node.auto_reviewed"
    NODE_EXEC_STARTED = "node.exec.started"
    NODE_EXEC_THINKING = "node.exec.thinking"
    NODE_EXEC_TOOL_CALL = "node.exec.tool_call"
    NODE_EXEC_TOOL_RESULT = "node.exec.tool_result"
    NODE_EXEC_STREAM_CHUNK = "node.exec.stream_chunk"
    NODE_EXEC_FINISHED = "node.exec.finished"
    NODE_RECEIPT_POSTED = "node.receipt.posted"
    BRANCH_BLOCKED = "branch.blocked"
    BRANCH_UNBLOCKED = "branch.unblocked"
