from app.event_runtime.handlers.dag import DAG_EVENT_HANDLER_REGISTRY
from app.event_runtime.handlers.message import MESSAGE_EVENT_HANDLER_REGISTRY
from app.event_runtime.handlers.system import SYSTEM_EVENT_HANDLER_REGISTRY
from app.event_runtime.handlers.task import TASK_EVENT_HANDLER_REGISTRY

EVENT_HANDLER_REGISTRY = (
    MESSAGE_EVENT_HANDLER_REGISTRY
    | DAG_EVENT_HANDLER_REGISTRY
    | TASK_EVENT_HANDLER_REGISTRY
    | SYSTEM_EVENT_HANDLER_REGISTRY
)

__all__ = [
    "EVENT_HANDLER_REGISTRY",
    "MESSAGE_EVENT_HANDLER_REGISTRY",
    "DAG_EVENT_HANDLER_REGISTRY",
    "TASK_EVENT_HANDLER_REGISTRY",
    "SYSTEM_EVENT_HANDLER_REGISTRY",
]
